name: Issue - Auto branch on "in progress"

on:
  issues:
    types: [labeled]

permissions:
  contents: write
  issues: write

jobs:
  create-branch:
    if: github.event.action == 'labeled' && github.event.label.name == 'in progress'
    runs-on: ubuntu-latest
    steps:
      - name: Create issue branch if missing and comment
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue = context.payload.issue;

            const { data: repoData } = await github.repos.get({ owner, repo });
            const defaultBranch = repoData.default_branch;

            const raw = issue.title || '';
            const slug = raw.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-+|-+$)/g,'').slice(0,30) || `${issue.number}`;
            const branch = `issue-${issue.number}-${slug}`;

            // Get SHA of default branch
            const { data: baseRef } = await github.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` });
            const baseSha = baseRef.object.sha;

            // Check if branch exists; create if missing
            let created = false;
            try {
              await github.git.getRef({ owner, repo, ref: `heads/${branch}` });
            } catch (e) {
              if (e.status === 404) {
                await github.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseSha });
                created = true;
              } else {
                throw e;
              }
            }

            const url = `https://github.com/${owner}/${repo}/tree/${branch}`;
            const msg = created
              ? `Automatisch erstellter Branch: ${branch}\n\n${url}`
              : `Branch existiert bereits: ${branch}\n\n${url}`;

            await github.issues.createComment({ owner, repo, issue_number: issue.number, body: msg });
